### ISSUE TITLE
LRUD Spatial still selecting elements that aren't visually the closest in EPT

### ISSUE THREAD

**Issue by ShiningTrapez** [bbc/lrud-spatial#26]
**Describe the bug**
#11; Nowhere near as bad now, but still an issue with certain menu layouts.

**To Reproduce**
1. Launch EPT in Chrome (MacOS).
2. Attempt to navigate down from, for example, "[L2Vod] [HD] | Gardener's World".
3. Observe an entire row of buttons is skipped over.

**Expected behavior**
An element in the row of buttons directly under the currently selected element should have been selected.

**Comment by jordanholt** [comment]
👋  Is this still a bug you're seeing on the latest version? I can't seem to reproduce it on EPT.
