### ISSUE TITLE
Navigation Unusable on Panasonic TV 2019 MT5813 FVP

### ISSUE THREAD

**Issue by ShiningTrapez** [bbc/lrud-spatial#27]
**Describe the bug**
Not tested on other devices, but we have observed the menu being far more skippy than the situation in #11, to the point of unusability.

**To Reproduce**
1. Launch EPT on Panasonic TV 2019 MT5813 FVP.
2. Attempt to Navigate Menus.
3. Observe Major Skipping of Elements.

**Expected behavior**
Menu is navigatable as would be intuitively expected.

**Comment by JohnPaulHarold** [comment]
@ShiningTrapez what commit closed this issue?

**Comment by jordanholt** [comment]
Hey @JohnPaulHarold, this was closed in https://github.com/bbc/lrud-spatial/pull/25. The issue wasn't device specific
