### ISSUE TITLE
Deprecated keyCode property in KeyboardEvent

### ISSUE THREAD

**Issue by wielorzeczownik** [bbc/lrud-spatial#31]
**Description:**
Currently, the use of the `keyCode` property in the `KeyboardEvent` object is not recommended. I suggest you consider adding the ability to use both `key` and `keyCode` interchangeably.

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by jordanholt** [comment]
Thanks flagging to us @wielorzeczownik, got a PR up to address this.
